年度更新により連絡先を更新
sitmathclub/sitmathclub.github.io pull request #28
Opened 2024-06-03 07:49 UTC by ack61

2024-06-03 07:55 UTC, MorIriT commented
試し：大丈夫です

2024-06-03 08:39 UTC, Kyo-s-s requested changes

2024-06-03 08:39 UTC, Kyo-s-s commented on set/html/sub.html
> +    <li>bv22059あっとshibaura-it.ac.jp</li>
この4行以外の差分は無いほうがよいはずです。(改行コード？)

2024-06-03 08:43 UTC, ack61 commented on set/html/sub.html
> +    <li>bv22059あっとshibaura-it.ac.jp</li>
autocrlf は falseにしてあるのですが、なぜか出てしまっています

2024-06-03 12:41 UTC, Kyo-s-s commented
https://github.com/sitmathclub/sitmathclub.github.io/blob/feature/update/address/index.html#L45
更新履歴に部長/副部長更新の旨を記述したほうが良さそうです。

2024-06-03 12:41 UTC, Kyo-s-s approved these changes

2024-06-03 12:44 UTC, Kyo-s-s commented
> 試し：大丈夫です

Approveできていなさそう？

2024-06-08 07:25 UTC, Kyo-s-s approved these changes
LGTM

2024-06-08 08:32 UTC, merged